name: CD
on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+

jobs:
  deploy:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@master
      with:
        node-version: 16.3.0
    - name: Install Node modules
      run: npm install
    - name: Publish
      run: npm run publish
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
