name: CI
on:
  push:
    branches: ['**']
    tags-ignore: ['v[0-9]+.[0-9]+.[0-9]+']

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@master
      with:
        node-version: 16.3.0
    - name: Install Node modules
      run: npm install
    - name: Build
      run: npm run dist
    - name: Persist distribution
      uses: actions/upload-artifact@v1
      with:
        name: dist
        path: dist/
