name: CI
on:
  push:
    branches: ["**"]
    tags-ignore: ["v*"]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@master
      with:
        node-version: 17.5.0
    - name: Install Node modules
      run: npm install
    - name: Build
      run: npm run make
    - name: Persist distribution
      uses: actions/upload-artifact@v1
      with:
        name: package-${{ matrix.os }}
        path: out/make/
